'use client'

import { useEffect, useState } from 'react'
import { Shield, CheckCircle, AlertTriangle, XCircle, Download, ChevronRight, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import Sidebar from '@/components/Sidebar'
import { getUploadedProjects, SAMPLE_PROJECTS, type Project } from '@/lib/projects'

// Each project gets a deterministic fake similarity score based on its ID
function fakeScore(id: string): number {
  let hash = 0
  for (const c of id) hash = (hash * 31 + c.charCodeAt(0)) % 100
  return Math.max(12, Math.min(85, hash))
}

function getSeverity(score: number) {
  if (score < 30) return { color: '#34d399', label: 'Highly Original', icon: CheckCircle }
  if (score < 50) return { color: '#fbbf24', label: 'Moderate Overlap', icon: AlertTriangle }
  if (score < 70) return { color: '#fb923c', label: 'High Overlap', icon: AlertTriangle }
  return { color: '#f87171', label: 'Very High Overlap', icon: XCircle }
}

function ProgressBar({ value, color }: { value: number; color: string }) {
  return (
    <div style={{ height: 6, background: 'rgba(255,255,255,0.07)', borderRadius: 3, overflow: 'hidden' }}>
      <div style={{ height: '100%', width: `${value}%`, background: color, borderRadius: 3, transition: 'width 0.5s ease' }} />
    </div>
  )
}

function ReportCard({ project }: { project: Project }) {
  const overall = fakeScore(project.id)
  const s = getSeverity(overall)
  const breakdown = {
    'Problem Domain': Math.min(99, overall + Math.floor(fakeScore(project.id + 'pd') % 25)),
    'Methodology': Math.max(5, overall - Math.floor(fakeScore(project.id + 'me') % 20)),
    'Technology': Math.max(5, overall - Math.floor(fakeScore(project.id + 'te') % 30)),
    'Outcomes': Math.max(5, overall - Math.floor(fakeScore(project.id + 'ou') % 35)),
  }
  const [downloading, setDownloading] = useState(false)

  const handleDownload = () => {
    setDownloading(true)
    // Simulate PDF generation
    setTimeout(() => {
      const content = `ProjectSphere Originality Report\n================================\nProject: ${project.title}\nDomain: ${project.domain}\nInstitution: ${project.college}\nYear: ${project.year}\n\nOVERALL SIMILARITY: ${overall}%\nVerdict: ${s.label}\n\nBREAKDOWN:\n${Object.entries(breakdown).map(([k, v]) => `  ${k}: ${v}%`).join('\n')}\n\nGenerated by ProjectSphere on ${new Date().toLocaleDateString('en-IN')}`
      const blob = new Blob([content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `originality-report-${project.title.replace(/\s+/g, '-').toLowerCase()}.txt`
      a.click()
      URL.revokeObjectURL(url)
      setDownloading(false)
    }, 800)
  }

  return (
    <div style={{
      borderRadius: 16, background: 'rgba(255,255,255,0.03)',
      border: `1px solid ${s.color}25`, padding: '24px',
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 20 }}>
        <div>
          <div style={{ fontWeight: 800, fontSize: 16, marginBottom: 6 }}>{project.title}</div>
          <div style={{ display: 'flex', gap: 14, fontSize: 13, color: 'rgba(255,255,255,0.4)' }}>
            <span style={{ color: '#60a5fa', fontWeight: 600 }}>{project.domain}</span>
            <span>{project.college}</span>
            <span>{project.year}</span>
          </div>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexShrink: 0 }}>
          <span style={{ fontSize: 11, fontWeight: 700, padding: '4px 10px', borderRadius: 6, background: `${s.color}18`, color: s.color, border: `1px solid ${s.color}30` }}>
            {s.label}
          </span>
          <button
            onClick={handleDownload}
            disabled={downloading}
            style={{
              display: 'flex', alignItems: 'center', gap: 5, padding: '7px 12px', borderRadius: 8,
              background: downloading ? 'rgba(59,130,246,0.1)' : 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)', color: downloading ? '#60a5fa' : 'rgba(255,255,255,0.55)',
              fontSize: 12, fontWeight: 600, cursor: downloading ? 'not-allowed' : 'pointer',
              transition: 'all 0.15s',
            }}
          >
            {downloading
              ? <><RefreshCw style={{ width: 12, height: 12, animation: 'spin 0.8s linear infinite' }} /> Generating…</>
              : <><Download style={{ width: 13, height: 13 }} /> PDF</>
            }
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', gap: 24, alignItems: 'flex-start' }}>
        {/* Circular score */}
        <div style={{
          width: 90, height: 90, borderRadius: '50%', flexShrink: 0,
          background: `conic-gradient(${s.color} ${overall * 3.6}deg, rgba(255,255,255,0.06) 0deg)`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <div style={{
            width: 68, height: 68, borderRadius: '50%', background: 'hsl(222, 47%, 8%)',
            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          }}>
            <span style={{ fontSize: 18, fontWeight: 900, color: s.color, lineHeight: 1 }}>{overall}%</span>
            <span style={{ fontSize: 9, color: 'rgba(255,255,255,0.35)', marginTop: 2 }}>similarity</span>
          </div>
        </div>

        {/* Breakdown bars */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 12 }}>
          {Object.entries(breakdown).map(([key, val]) => {
            const sv = getSeverity(val)
            return (
              <div key={key}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 5 }}>
                  <span style={{ fontWeight: 600, color: 'rgba(255,255,255,0.65)' }}>{key}</span>
                  <span style={{ fontWeight: 700, color: sv.color }}>{val}%</span>
                </div>
                <ProgressBar value={val} color={sv.color} />
              </div>
            )
          })}
        </div>
      </div>

      <div style={{ marginTop: 16, display: 'flex', justifyContent: 'flex-end' }}>
        <Link href={`/project/${project.id}`} style={{ fontSize: 12, fontWeight: 600, color: '#60a5fa', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 4 }}>
          View Project <ChevronRight style={{ width: 13, height: 13 }} />
        </Link>
      </div>
    </div>
  )
}

export default function ReportsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [tab, setTab] = useState<'mine' | 'sample'>('mine')

  useEffect(() => {
    setProjects(getUploadedProjects())
  }, [])

  const displayed = tab === 'mine' ? projects : SAMPLE_PROJECTS.slice(0, 3)

  return (
    <div style={{ minHeight: '100vh', background: 'hsl(222, 47%, 6%)', color: 'hsl(210, 40%, 96%)', fontFamily: 'Inter, system-ui, sans-serif', display: 'flex' }}>
      <Sidebar />

      <main style={{ flex: 1, padding: '32px', overflowY: 'auto', minWidth: 0 }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 12 }}>
          <div style={{ width: 44, height: 44, borderRadius: 12, background: 'rgba(52,211,153,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Shield style={{ width: 22, height: 22, color: '#34d399' }} />
          </div>
          <h1 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.5px' }}>Originality Reports</h1>
        </div>
        <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: 14, marginBottom: 28 }}>
          Detailed originality analysis for your projects. Click PDF to download a full report.
        </p>

        {/* Tabs */}
        <div style={{ display: 'flex', gap: 8, marginBottom: 28 }}>
          <button onClick={() => setTab('mine')} style={{ padding: '8px 18px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', border: 'none', background: tab === 'mine' ? 'rgba(52,211,153,0.12)' : 'rgba(255,255,255,0.05)', color: tab === 'mine' ? '#34d399' : 'rgba(255,255,255,0.5)' }}>
            My Projects ({projects.length})
          </button>
          <button onClick={() => setTab('sample')} style={{ padding: '8px 18px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', border: 'none', background: tab === 'sample' ? 'rgba(52,211,153,0.12)' : 'rgba(255,255,255,0.05)', color: tab === 'sample' ? '#34d399' : 'rgba(255,255,255,0.5)' }}>
            Sample Reports
          </button>
        </div>

        {/* Reports */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, maxWidth: 860 }}>
          {displayed.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '60px 0', color: 'rgba(255,255,255,0.3)' }}>
              <Shield style={{ width: 48, height: 48, margin: '0 auto 16px', opacity: 0.2 }} />
              <p style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>No projects yet</p>
              <p style={{ fontSize: 14, marginBottom: 20 }}>Upload a project to get an originality report.</p>
              <Link href="/upload" style={{ padding: '10px 20px', borderRadius: 9, background: '#34d399', color: '#0d1117', fontSize: 14, fontWeight: 700, textDecoration: 'none' }}>
                Upload Project
              </Link>
            </div>
          ) : (
            displayed.map(p => <ReportCard key={p.id} project={p} />)
          )}
        </div>

        {/* CTA */}
        <div style={{
          marginTop: 28, maxWidth: 860,
          background: 'linear-gradient(135deg, rgba(52,211,153,0.06), rgba(59,130,246,0.06))',
          border: '1px solid rgba(52,211,153,0.15)', borderRadius: 16, padding: '24px 28px',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20,
        }}>
          <div>
            <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 6 }}>Want to check a new project?</h3>
            <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: 13 }}>Run an instant similarity check before uploading.</p>
          </div>
          <Link href="/similarity" style={{
            display: 'flex', alignItems: 'center', gap: 6, background: '#34d399', color: '#0d1117',
            padding: '11px 20px', borderRadius: 9, fontSize: 14, fontWeight: 800, textDecoration: 'none',
          }}>
            Run Check <ChevronRight style={{ width: 15, height: 15 }} />
          </Link>
        </div>
      </main>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}
