'use client'

import Link from 'next/link'
import { ArrowLeft, Lightbulb, TrendingUp, TrendingDown, BarChart2, Search, Zap, ChevronRight } from 'lucide-react'

const OVERCROWDED = [
  { topic: 'Face Recognition Attendance', count: 89, growth: -12 },
  { topic: 'Weather Prediction App', count: 67, growth: -8 },
  { topic: 'Student Result Management', count: 54, growth: -15 },
  { topic: 'Hospital Management System', count: 48, growth: -5 },
  { topic: 'E-commerce Website', count: 43, growth: -20 },
]

const EMERGING = [
  { topic: 'Federated Learning for Privacy', count: 4, growth: 340, domain: 'AI & ML', opportunity: 'Very High' },
  { topic: 'Quantum-safe Cryptography', count: 2, growth: 280, domain: 'Cybersecurity', opportunity: 'Very High' },
  { topic: 'Digital Twin Infrastructure', count: 6, growth: 210, domain: 'IoT', opportunity: 'High' },
  { topic: 'Neuromorphic Computing', count: 1, growth: 190, domain: 'AI & ML', opportunity: 'Very High' },
  { topic: 'AI for Vernacular Languages', count: 8, growth: 175, domain: 'AI & ML', opportunity: 'High' },
  { topic: 'Sustainable Computing', count: 3, growth: 160, domain: 'Green Tech', opportunity: 'High' },
]

const DOMAIN_INSIGHTS = [
  { domain: 'AI & ML', projects: 342, avgSim: 56, gaps: ['Explainability tools for Indian legal domain', 'AI for Tribal language preservation'], color: '#60a5fa' },
  { domain: 'IoT', projects: 198, avgSim: 48, gaps: ['Smart agriculture for arid zones', 'IoT for underground mining safety'], color: '#34d399' },
  { domain: 'Cybersecurity', projects: 87, avgSim: 41, gaps: ['Post-quantum network protocols', 'Security auditing for microservices'], color: '#f87171' },
  { domain: 'Blockchain', projects: 134, avgSim: 53, gaps: ['Decentralized identity for refugees', 'Blockchain voting for local governance'], color: '#c084fc' },
]

const oppColor: Record<string, string> = {
  'Very High': '#34d399',
  'High': '#60a5fa',
  'Moderate': '#fbbf24',
}

const domainColor: Record<string, string> = {
  'AI & ML': '#60a5fa',
  'Cybersecurity': '#f87171',
  'IoT': '#34d399',
  'Green Tech': '#2dd4bf',
}

export default function InsightsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'hsl(222, 47%, 6%)', color: 'hsl(210, 40%, 96%)', fontFamily: 'Inter, system-ui, sans-serif' }}>
      {/* Top bar */}
      <div style={{
        borderBottom: '1px solid rgba(255,255,255,0.07)',
        background: 'rgba(10,13,20,0.9)', backdropFilter: 'blur(20px)',
        padding: '0 24px', height: 60, display: 'flex', alignItems: 'center', gap: 16,
        position: 'sticky', top: 0, zIndex: 40,
      }}>
        <Link href="/dashboard" style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'rgba(255,255,255,0.5)', textDecoration: 'none', fontSize: 14 }}>
          <ArrowLeft style={{ width: 16, height: 16 }} /> Dashboard
        </Link>
        <span style={{ color: 'rgba(255,255,255,0.2)' }}>/</span>
        <span style={{ fontSize: 14, fontWeight: 600 }}>Innovation Insights</span>
      </div>

      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '40px 24px' }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 12 }}>
          <div style={{ width: 44, height: 44, borderRadius: 12, background: 'rgba(251,191,36,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Lightbulb style={{ width: 22, height: 22, color: '#fbbf24' }} />
          </div>
          <h1 style={{ fontSize: 28, fontWeight: 800, letterSpacing: '-0.5px' }}>Innovation Insights</h1>
        </div>
        <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: 15, marginBottom: 40 }}>
          Discover what&apos;s been over-explored, what research gaps exist, and where you can build something genuinely new.
        </p>

        {/* Alert Banner */}
        <div style={{
          background: 'rgba(59,130,246,0.07)', border: '1px solid rgba(59,130,246,0.2)',
          borderRadius: 14, padding: '16px 20px', marginBottom: 32,
          display: 'flex', gap: 12, alignItems: 'center',
        }}>
          <Zap style={{ width: 20, height: 20, color: '#60a5fa', flexShrink: 0 }} />
          <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.65)', lineHeight: 1.6 }}>
            Insights are generated by analyzing <strong style={{ color: 'white' }}>1,200+ student projects</strong> across 50+ institutions. The emerging topics are identified by tracking submission velocity, citation patterns, and domain activity.
          </p>
        </div>

        {/* Two-column */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, marginBottom: 28 }}>
          {/* Overcrowded */}
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 16, padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
              <TrendingDown style={{ width: 18, height: 18, color: '#f87171' }} />
              <h2 style={{ fontWeight: 700, fontSize: 16 }}>Over-Explored Areas</h2>
              <span style={{ fontSize: 11, padding: '2px 8px', borderRadius: 6, background: 'rgba(239,68,68,0.1)', color: '#f87171', fontWeight: 700, marginLeft: 'auto' }}>Avoid</span>
            </div>
            <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.4)', marginBottom: 18, lineHeight: 1.6 }}>
              These topics have been heavily covered. Projects in these areas score higher on similarity and have less impact potential.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {OVERCROWDED.map((item, i) => (
                <div key={item.topic} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <span style={{ fontSize: 14, fontWeight: 900, color: 'rgba(255,255,255,0.15)', width: 20, textAlign: 'center' }}>{i + 1}</span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{item.topic}</div>
                    <div style={{ height: 4, background: 'rgba(255,255,255,0.06)', borderRadius: 2, overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${(item.count / 100) * 100}%`, background: '#f87171', borderRadius: 2 }} />
                    </div>
                  </div>
                  <span style={{ fontSize: 12, fontWeight: 700, color: '#f87171', whiteSpace: 'nowrap' }}>{item.count} projects</span>
                </div>
              ))}
            </div>
          </div>

          {/* Emerging */}
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 16, padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
              <TrendingUp style={{ width: 18, height: 18, color: '#34d399' }} />
              <h2 style={{ fontWeight: 700, fontSize: 16 }}>Emerging Opportunities</h2>
              <span style={{ fontSize: 11, padding: '2px 8px', borderRadius: 6, background: 'rgba(52,211,153,0.1)', color: '#34d399', fontWeight: 700, marginLeft: 'auto' }}>Explore</span>
            </div>
            <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.4)', marginBottom: 18, lineHeight: 1.6 }}>
              These areas are gaining traction but remain underserved. High originality potential with significant real-world impact.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {EMERGING.map(item => (
                <div key={item.topic} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 12px', borderRadius: 10, background: 'rgba(52,211,153,0.04)', border: '1px solid rgba(52,211,153,0.1)' }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{item.topic}</div>
                    <span style={{ fontSize: 11, fontWeight: 700, color: domainColor[item.domain] || '#60a5fa' }}>{item.domain}</span>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: 13, fontWeight: 700, color: '#34d399' }}>+{item.growth}%</div>
                    <div style={{ fontSize: 11, color: oppColor[item.opportunity] || '#60a5fa', fontWeight: 600 }}>{item.opportunity}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Domain Gaps */}
        <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 16, padding: '28px', marginBottom: 28 }}>
          <h2 style={{ fontWeight: 700, fontSize: 18, marginBottom: 6 }}>Research Gaps by Domain</h2>
          <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: 14, marginBottom: 24 }}>Specific unsolved problems within each domain — curated from project abstracts and faculty feedback.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 16 }}>
            {DOMAIN_INSIGHTS.map(d => (
              <div key={d.domain} style={{
                padding: '20px', borderRadius: 12, background: 'rgba(255,255,255,0.02)',
                border: `1px solid ${d.color}22`,
              }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
                  <span style={{ fontSize: 14, fontWeight: 800, color: d.color }}>{d.domain}</span>
                  <div style={{ display: 'flex', gap: 12, fontSize: 12, color: 'rgba(255,255,255,0.35)' }}>
                    <span>{d.projects} projects</span>
                    <span>avg sim: {d.avgSim}%</span>
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {d.gaps.map(gap => (
                    <div key={gap} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 13, color: 'rgba(255,255,255,0.65)', lineHeight: 1.5 }}>
                      <span style={{ color: d.color, flexShrink: 0, marginTop: 2 }}>→</span>
                      {gap}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{
          background: 'linear-gradient(135deg, rgba(59,130,246,0.08), rgba(139,92,246,0.08))',
          border: '1px solid rgba(99,102,241,0.2)', borderRadius: 16, padding: '28px',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20,
        }}>
          <div>
            <h3 style={{ fontWeight: 700, fontSize: 18, marginBottom: 8 }}>Ready to check how original your idea is?</h3>
            <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: 14 }}>Run a full similarity analysis on your project description.</p>
          </div>
          <Link href="/similarity" style={{
            display: 'flex', alignItems: 'center', gap: 8, background: '#6366f1', color: 'white',
            padding: '12px 22px', borderRadius: 10, fontSize: 14, fontWeight: 700, textDecoration: 'none',
            whiteSpace: 'nowrap', boxShadow: '0 4px 14px rgba(99,102,241,0.3)',
          }}>
            Check Similarity <ChevronRight style={{ width: 16, height: 16 }} />
          </Link>
        </div>
      </div>
    </div>
  )
}
